/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Conexion.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dabo7
 */
public class ConsultaCCMostrar extends javax.swing.JFrame {
    PreparedStatement PS;
    Conectar CN;
    ResultSet rs;
    /**
     * Creates new form ConsultaCCMostrar
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public ConsultaCCMostrar() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ConsuE = new javax.swing.JTextField();
        BtnVolverCons = new javax.swing.JButton();
        BtnConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Herencia.exe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIGITE LA CEDULA QUE QUIERE CONSULTAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 27, -1, -1));

        ConsuE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ConsuE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsuEActionPerformed(evt);
            }
        });
        ConsuE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ConsuEKeyTyped(evt);
            }
        });
        getContentPane().add(ConsuE, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 66, 303, -1));

        BtnVolverCons.setText("Volver");
        BtnVolverCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverConsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolverCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 84, 79, -1));

        BtnConsultar.setText("Consultar");
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/37201_fonds-decran-street-art-tous-les-wallpapers-street-art_1920x1200_h.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsuEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsuEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsuEActionPerformed

    private void BtnVolverConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverConsActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolverConsActionPerformed

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        String BusCed;
        BusCed= ConsuE.getText();
        PS = null;
        CN = new Conectar();
        Connection con ;
        try{
            
            con = CN.getConnection();
            PS= con.prepareStatement("SELECT * FROM registro WHERE Cedula = ? ");
            PS.setString(1,BusCed);
            rs= PS.executeQuery();
            if(rs.next())
            {
                Mostrar mos = new Mostrar();
                mos.pack();
                mos.setVisible(true);
                Mostrar.Ced.setText(rs.getString("Cedula"));
                Mostrar.Nom.setText(rs.getString("Nombre"));
                Mostrar.Tel.setText(rs.getString("Telefono"));
                Mostrar.Hor.setText(rs.getString("Horas"));
                Mostrar.ValHo.setText(rs.getString("ValorH"));
                Mostrar.Suel.setText(rs.getString("Salario"));
                 if(rs.getInt("Horas")<=40){
                        Mostrar.HES.setText("0");
                        Mostrar.ValorAPagar1.setText("0");
                        Mostrar.HED.setText("0");
                        Mostrar.ValorAPagar2.setText("0");
                    }else
                    {
                        if(rs.getInt("Horas")<=48)
                        {
                            Mostrar.HES.setText(String.valueOf(rs.getInt("Horas")-40));
                            Mostrar.ValorAPagar1.setText(String.valueOf(((rs.getInt("ValorH")*20/100)+rs.getInt("ValorH"))*(rs.getInt("Horas")-40)));
                            Mostrar.HED.setText("0");
                            Mostrar.ValorAPagar2.setText("0");
                        }else
                        {
                            Mostrar.HES.setText("8");
                            Mostrar.ValorAPagar1.setText(String.valueOf(((rs.getInt("ValorH")*20/100)+rs.getInt("ValorH"))*8));
                            Mostrar.HED.setText(String.valueOf(rs.getInt("Horas")-48));
                            Mostrar.ValorAPagar2.setText(String.valueOf(((rs.getInt("ValorH")*40/100)+rs.getInt("ValorH"))*(rs.getInt("Horas")-48))); 
                        }
                    }
            }
            else{
                if(BusCed.isEmpty())
                {
                     JOptionPane.showMessageDialog(null, "Porfavor Ingrese una cedula");
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro la cedula");
                }
            }
        } catch(Exception e){
            System.err.println(e);
        }       
    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void ConsuEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConsuEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ConsuE.getText().length()>=12){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_ConsuEKeyTyped

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCCMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new ConsultaCCMostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnVolverCons;
    private javax.swing.JTextField ConsuE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
