/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Conexion.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dabo7
 */
public class Eliminar extends javax.swing.JFrame {
    PreparedStatement PS;
    Conectar CN;
    ResultSet rs;
    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ElimE = new javax.swing.JTextField();
        BtnElminar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Herencia.exe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Que numero de cedula quiere elimiar?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        ElimE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ElimEKeyTyped(evt);
            }
        });
        getContentPane().add(ElimE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 171, -1));

        BtnElminar.setText("Eliminar");
        BtnElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnElminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 147, -1, -1));

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 147, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 310, 29));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/2feaeb66523229.Y3JvcCw5MjIsNzIyLDEzOCww.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElminarActionPerformed
        jLabel2.setText("");
        String ElimCed;
        ElimCed = ElimE.getText();
        if (ElimCed.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo de busqueda esta vacio", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            PS = null;
            CN = new Conectar();
            Connection con;
            try {
                con = CN.getConnection();
                PS= con.prepareStatement("SELECT * FROM registro WHERE Cedula = ? ");
                PS.setString(1, ElimCed);
                rs= PS.executeQuery();
                if(rs.next())
                {
                    if (JOptionPane.showConfirmDialog(rootPane, "Eliminar Registro!, ¿desea continuar?",
                            "Eliminar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        PS = con.prepareStatement("DELETE FROM registro WHERE Cedula = ?");
                        PS.setString(1, ElimCed);
                        int res = PS.executeUpdate();
                        jLabel2.setText("El registro se ha eliminado satisfactoriamente");
                    }
                }else {
                    if (ElimCed.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Porfavor ingrese una cedula", "Error", JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontro la cedula", "Error", JOptionPane.WARNING_MESSAGE);
                    }
                }
                ElimE.setText("");
            }catch(Exception e){
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_BtnElminarActionPerformed

    private void ElimEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElimEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ElimE.getText().length()>=12){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_ElimEKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnElminar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextField ElimE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
