/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Conexion.Conectar;
import MisClases.Salario;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class Ingresar extends javax.swing.JFrame {
    
    PreparedStatement PS;
    Conectar CN;
    @SuppressWarnings("LeakingThisInConstructor")
    public Ingresar() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CedE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomE = new javax.swing.JTextField();
        TelE = new javax.swing.JTextField();
        BtnCargar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HorE = new javax.swing.JTextField();
        ValHoE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Herencia.exe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula:");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        CedE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedEActionPerformed(evt);
            }
        });
        CedE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedEKeyTyped(evt);
            }
        });
        getContentPane().add(CedE, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 30, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        NomE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomEActionPerformed(evt);
            }
        });
        NomE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomEKeyTyped(evt);
            }
        });
        getContentPane().add(NomE, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 68, 100, -1));

        TelE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelEActionPerformed(evt);
            }
        });
        TelE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelEKeyTyped(evt);
            }
        });
        getContentPane().add(TelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 106, 100, -1));

        BtnCargar.setText("Cargar");
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 244, -1, -1));

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 244, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Horas: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Horas: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 184, -1, 20));

        HorE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorEActionPerformed(evt);
            }
        });
        HorE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HorEKeyTyped(evt);
            }
        });
        getContentPane().add(HorE, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 144, 100, -1));

        ValHoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValHoEKeyTyped(evt);
            }
        });
        getContentPane().add(ValHoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 182, 100, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/3229553817_6aaaeca1f7_b.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomEActionPerformed

    private void TelEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelEActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed
        String Ced2, Nomb2, Tele2, ValH2, Hor2;
        int Suel;
        Salario calc = new Salario();
        ValH2 = ValHoE.getText();
        Hor2 = HorE.getText();
        Ced2 = CedE.getText();
        Nomb2 = NomE.getText();
        Tele2 = TelE.getText();
        Suel= calc.getResueldo();
        if (ValH2.isEmpty() || Hor2.isEmpty() || Ced2.isEmpty() || Nomb2.isEmpty() || Tele2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se pueden cargar datos en blanco ", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else {
            PS = null;
            CN = new Conectar();
            try {
                Salario aux = new Salario();
                aux.setNom(Nomb2);
                aux.setValorH(Integer.valueOf(ValH2));
                aux.setHoras(Integer.valueOf(Hor2));
                aux.setCed(Ced2);
                aux.setTel(Tele2);
                aux.setResueldo(Suel);
                PS = CN.getConnection().prepareStatement("INSERT INTO registro (Cedula,Nombre,Telefono,Horas,ValorH,Salario) values(?,?,?,?,?,?)");
                PS.setString(1, aux.getCed());
                PS.setString(2, aux.getNom());
                PS.setString(3, aux.getTel());
                PS.setInt(4, aux.getHoras());
                PS.setInt(5, aux.getValorH());
                PS.setInt(6, aux.getResueldo());
                int res = PS.executeUpdate();
                ValHoE.setText("");
                HorE.setText("");
                CedE.setText("");
                NomE.setText("");
                TelE.setText("");
                if (res > 0) {
                    JOptionPane.showMessageDialog(null,"Registro Guardado ");
                } else {
                    JOptionPane.showMessageDialog(null,"El registro no pudo ser guardado");

                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null,"Esta Cedula ya se encuentra en el sistema");
            }
            
        }
    }//GEN-LAST:event_BtnCargarActionPerformed


    private void CedEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedEActionPerformed

    private void HorEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorEActionPerformed

    private void CedEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(CedE.getText().length()>=12){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_CedEKeyTyped

    private void NomEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(NomE.getText().length()>=20){
            evt.consume();
        }
        if(Character.isDigit(val)||(val2>=33 && val2<=47)||(val2>=58 && val2<=64)||(val2>=91 && val2<=96)||(val2>=123 && val2<=163)|| (val2>=166 && val2<=223))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
        }
    }//GEN-LAST:event_NomEKeyTyped

    private void TelEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(TelE.getText().length()>=10){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_TelEKeyTyped

    private void HorEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HorEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(HorE.getText().length()>=3){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_HorEKeyTyped

    private void ValHoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValHoEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ValHoE.getText().length()>=5){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_ValHoEKeyTyped

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new Ingresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargar;
    private javax.swing.JButton BtnVolver;
    public static javax.swing.JTextField CedE;
    private javax.swing.JTextField HorE;
    public static javax.swing.JTextField NomE;
    public static javax.swing.JTextField TelE;
    private javax.swing.JTextField ValHoE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
