/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Conexion.Conectar;
import MisClases.Salario;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author dabo7
 */
public class Modificar extends javax.swing.JFrame {

    PreparedStatement PS;
    Conectar CN;
    ResultSet rs;

    /**
     * Creates new form Modificar
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public Modificar() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ModifE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ModifNom = new javax.swing.JTextField();
        ModifTel = new javax.swing.JTextField();
        ModifHor = new javax.swing.JTextField();
        ModifValH = new javax.swing.JTextField();
        ModifSuel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Herencia.exe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Que numero de cedula quiere modificar?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 34, -1, -1));

        ModifE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModifEKeyTyped(evt);
            }
        });
        getContentPane().add(ModifE, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 70, 152, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Horas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 42, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Valor Hora");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 59, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Sueldo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, -1));

        ModifNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModifNomKeyTyped(evt);
            }
        });
        getContentPane().add(ModifNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 110, 110, -1));

        ModifTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModifTelKeyTyped(evt);
            }
        });
        getContentPane().add(ModifTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 148, 110, -1));

        ModifHor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModifHorKeyTyped(evt);
            }
        });
        getContentPane().add(ModifHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 186, 110, -1));

        ModifValH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModifValHKeyTyped(evt);
            }
        });
        getContentPane().add(ModifValH, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 224, 110, -1));

        ModifSuel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ModifSuel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ModifSuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 110, 14));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 69, -1, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 169, -1, -1));

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/unnamed.jpg"))); // NOI18N
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PS = null;
        CN = new Conectar();
        Connection con;
        String BusCed2;
        BusCed2 = ModifE.getText();
        try {
            con = CN.getConnection();
            PS = con.prepareStatement("SELECT * FROM registro WHERE Cedula = ? ");
            PS.setString(1, BusCed2);
            rs = PS.executeQuery();
            if (rs.next()) {
                ModifNom.setText(rs.getString("Nombre"));
                ModifTel.setText(rs.getString("Telefono"));
                ModifHor.setText(String.valueOf(rs.getInt("Horas")));
                ModifValH.setText(String.valueOf(rs.getInt("ValorH")));
                ModifSuel.setText(String.valueOf(rs.getString("Salario")));
            } else {
                ModifNom.setText("");
                ModifTel.setText("");
                ModifHor.setText("");
                ModifValH.setText("");
                ModifSuel.setText("");
                if (BusCed2.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Porfavor Ingrese una cedula");
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontro la cedula");
                }
            }
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Hor, Mod, Nom, Tel, ValH, BusCed2;
        int Suel;
        Salario calc = new Salario();
        ValH = ModifValH.getText();
        Hor = ModifHor.getText();
        Nom = ModifNom.getText();
        Tel = ModifTel.getText();
        Suel = calc.getResueldo();
        BusCed2 = ModifE.getText();
        PS = null;
        CN = new Conectar();
        if (BusCed2.isEmpty()||Nom.isEmpty()|Tel.isEmpty()||ValH.isEmpty()||Hor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay cedula a la cual se le puedan modificar datos o los datos estan incompletos ");
        } else {
            try {
                Salario aux = new Salario();
                aux.setNom(Nom);
                aux.setValorH(Integer.valueOf(ValH));
                aux.setHoras(Integer.valueOf(Hor));
                aux.setTel(Tel);
                aux.setResueldo(Suel);
                PS = CN.getConnection().prepareStatement("UPDATE registro SET Nombre = ?,Telefono = ?,Horas = ?, ValorH = ?, Salario = ? WHERE Cedula = ?");
                PS.setString(1, aux.getNom());
                PS.setString(2, aux.getTel());
                PS.setInt(3, aux.getHoras());
                PS.setInt(4, aux.getValorH());
                PS.setInt(5, aux.getResueldo());
                PS.setString(6, BusCed2);
                int res = PS.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Registro Modificado ");
                } else {
                    JOptionPane.showMessageDialog(null, "El registro no pudo ser modificado");
                }
            } catch (HeadlessException | SQLException e) {
                System.err.println("Error al Cargar " + e.getMessage());
            }
            ModifE.setText("");
            ModifNom.setText("");
            ModifTel.setText("");
            ModifHor.setText("");
            ModifValH.setText("");
            ModifSuel.setText("");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ModifEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModifEKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ModifE.getText().length()>=12){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_ModifEKeyTyped

    private void ModifNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModifNomKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ModifNom.getText().length()>=20){
            evt.consume();
        }
        if(Character.isDigit(val)||(val2>=33 && val2<=47)||(val2>=58 && val2<=64)||(val2>=91 && val2<=96)||(val2>=123 && val2<=163)|| (val2>=166 && val2<=223))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
        }
    }//GEN-LAST:event_ModifNomKeyTyped

    private void ModifTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModifTelKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ModifTel.getText().length()>=10){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_ModifTelKeyTyped

    private void ModifHorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModifHorKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ModifHor.getText().length()>=3){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_ModifHorKeyTyped

    private void ModifValHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModifValHKeyTyped
        char val=evt.getKeyChar();
        int val2 = evt.getKeyChar();
        if(ModifValH.getText().length()>=5){
            evt.consume();
        }
        if(Character.isLetter(val)|| (val2>=32 && val2<= 46)||(val2>=58 && val2<= 64)|| (val2>=91 && val2<= 96)||(val2>=133 && val2<= 255))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_ModifValHKeyTyped

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ModifE;
    private javax.swing.JTextField ModifHor;
    private javax.swing.JTextField ModifNom;
    private javax.swing.JLabel ModifSuel;
    private javax.swing.JTextField ModifTel;
    private javax.swing.JTextField ModifValH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
