/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author dabo7
 */
public class Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ced = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        Hor = new javax.swing.JLabel();
        ValHo = new javax.swing.JLabel();
        BtnVol = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Suel = new javax.swing.JLabel();
        HorasExSim = new javax.swing.JLabel();
        HES = new javax.swing.JLabel();
        SPA2 = new javax.swing.JLabel();
        ValorAPagar1 = new javax.swing.JLabel();
        HorasExtrasDob = new javax.swing.JLabel();
        SPA1 = new javax.swing.JLabel();
        HED = new javax.swing.JLabel();
        ValorAPagar2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Herencia.exe");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("La cedula esta en la base de datos ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 38, -1, -1));

        Label.setForeground(new java.awt.Color(255, 255, 255));
        Label.setText("Cedula :");
        getContentPane().add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Horas totales:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor Hora :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        Ced.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ced.setForeground(new java.awt.Color(255, 255, 255));
        Ced.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Ced, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 80, 21));

        Nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nom.setForeground(new java.awt.Color(255, 255, 255));
        Nom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 73, 20));

        Tel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tel.setForeground(new java.awt.Color(255, 255, 255));
        Tel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, 21));

        Hor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Hor.setForeground(new java.awt.Color(255, 255, 255));
        Hor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Hor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 60, 21));

        ValHo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ValHo.setForeground(new java.awt.Color(240, 240, 240));
        ValHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ValHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, 21));

        BtnVol.setText("Volver");
        BtnVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 280, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sueldo total :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        Suel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Suel.setForeground(new java.awt.Color(240, 240, 240));
        Suel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Suel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, 21));

        HorasExSim.setForeground(new java.awt.Color(255, 255, 255));
        HorasExSim.setText("Las horas extras simples son :");
        getContentPane().add(HorasExSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 20));

        HES.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HES.setForeground(new java.awt.Color(240, 240, 240));
        HES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(HES, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, 20));

        SPA2.setForeground(new java.awt.Color(240, 240, 240));
        SPA2.setText("Valor a pagar :");
        getContentPane().add(SPA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 20));

        ValorAPagar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ValorAPagar1.setForeground(new java.awt.Color(240, 240, 240));
        ValorAPagar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ValorAPagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 110, 20));

        HorasExtrasDob.setForeground(new java.awt.Color(240, 240, 240));
        HorasExtrasDob.setText("Las horas extras dobles son :");
        getContentPane().add(HorasExtrasDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 20));

        SPA1.setForeground(new java.awt.Color(255, 255, 255));
        SPA1.setText("Valor a pagar :");
        getContentPane().add(SPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, 20));

        HED.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HED.setForeground(new java.awt.Color(240, 240, 240));
        HED.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(HED, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 60, 20));

        ValorAPagar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ValorAPagar2.setForeground(new java.awt.Color(240, 240, 240));
        ValorAPagar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ValorAPagar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 80, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/hipertextual-todo-nuevo-reestreno-spider-man-lejos-casa-2019954221.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVol;
    public static javax.swing.JLabel Ced;
    public static javax.swing.JLabel HED;
    public static javax.swing.JLabel HES;
    public static javax.swing.JLabel Hor;
    private javax.swing.JLabel HorasExSim;
    private javax.swing.JLabel HorasExtrasDob;
    private javax.swing.JLabel Label;
    public static javax.swing.JLabel Nom;
    private javax.swing.JLabel SPA1;
    private javax.swing.JLabel SPA2;
    public static javax.swing.JLabel Suel;
    public static javax.swing.JLabel Tel;
    public static javax.swing.JLabel ValHo;
    public static javax.swing.JLabel ValorAPagar1;
    public static javax.swing.JLabel ValorAPagar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
